export const categoryKeywords = {
  Verduras: [
    "acelga",
    "ajo",
    "alcaucil",
    "apio",
    "batata",
    "berenjena",
    "berro",
    "brocoli",
    "brócoli",
    "calabaza",
    "cebolla",
    "choclo",
    "coliflor",
    "esparragos",
    "esparragos",
    "espinaca",
    "lechuga",
    "morron",
    "morrón",
    "nabo",
    "palta",
    "papa",
    "pepino",
    "puerro",
    "rabanito",
    "radicheta",
    "remolacha",
    "repollo",
    "repollo de brucelas",
    "tomate",
    "zanahoria",
    "zapallito",
    "verdeo",
    "zapallo",
    "zukini",
    "zucchini",
  ],
  Frutas: [
    "anana",
    "ananá",
    "arandanos",
    "arándanos",
    "banana",
    "cayote",
    "cereza",
    "ciruela",
    "damasco",
    "durazno",
    "frutilla",
    "frutos rojos",
    "granada",
    "higo",
    "kiwi",
    "lima",
    "limon",
    "limón",
    "mandarina",
    "mango",
    "manzana",
    "maracuya",
    "maracuyá",
    "melon",
    "melón",
    "naranja",
    "papaya",
    "pelones",
    "pera",
    "platano",
    "plátano",
    "pomelo",
    "quinotos",
    "sandia",
    "sandía",
    "tanjarina",
    "uva",
  ],
  Aromaticas: [
    "yerba buena",
    "tomillo",
    "salvia",
    "romero",
    "provenzal",
    "perejil",
    "oregano",
    "orégano",
    "nuez moscada",
    "rucula",
    "rúcula",
    "jengibre",
    "menta",
    "laurel",
    "hinojo",
    "estevia",
    "comino",
    "cilantro",
    "canela",
    "albahaca",
    "aji",
    "ají",
  ],
  "Frutos secos y granos": [
    "almendras",
    "arvejas",
    "brote de soja",
    "chaucha",
    "chia",
    "garbanzo",
    "habas",
    "lenteja",
    "maiz pelado",
    "maíz pelado",
    "mani",
    "maní",
    "nuez",
    "porotos",
    "quinoa",
  ],
  Otros: [],
};
