export const unitsCatalog = [
  "Kg",
  "Cajón",
  "Caja",
  "Bandeja",
  "Jaula",
  "Jaula Grande",
  "Bolsa",
  "Docena",
  "Maple",
  "Horma",
  "Pote",
  "Atado",
  "Unidad",
  "Cabeza",
  "Ristra",
  "Entero",
];

export const singleUnitByName = new Map([
  ["espinaca", "Atado"],
  ["acelga", "Atado"],
  ["albahaca", "Atado"],
  ["apio", "Atado"],
  ["menta", "Atado"],
  ["menta o yerba buena", "Atado"],
  ["perejil", "Atado"],
  ["puerro", "Atado"],
  ["verdeo", "Atado"],
  ["brocoli", "Unidad"],
  ["berro", "Unidad"],
  ["coliflor", "Unidad"],
  ["esparragos", "Unidad"],
  ["laurel", "Unidad"],
  ["sandia", "Unidad"],
  ["anana", "Unidad"],
]);

export const fixedUnitsByName = new Map([
  ["aji", ["Kg"]],
  ["aji picante", ["Kg"]],
  ["canela en rama", ["Kg"]],
  ["cilantro", ["Kg"]],
  ["habas", ["Kg"]],
  ["frutos rojos", ["Kg"]],
  ["hinojo", ["Kg"]],
  ["maracuya", ["Kg"]],
  ["nuez moscada", ["Kg"]],
  ["nabos", ["Kg"]],
  ["oregano", ["Kg"]],
  ["tomillo", ["Kg"]],
  ["quinoa", ["Kg"]],
  ["remolacha", ["Atado"]],
  ["repollo", ["Kg"]],
  ["yerba buena", ["Kg"]],
  ["queso", ["Kg", "Horma"]],
  ["pomelo", ["Jaula", "Docena", "Jaula Grande"]],
]);

export const unitModeProducts = new Set([
  "batata",
  "berenjena",
  "berenjenas",
  "calabaza",
  "cayote",
  "cebolla",
  "choclo",
  "damasco",
  "durazno",
  "duraznos",
  "granada",
  "higo",
  "higos",
  "jengibre",
  "kiwi",
  "kiwis",
  "mango",
  "maracuya",
  "manzana",
  "morron",
  "morrones",
  "palta",
  "papaya",
  "pera",
  "peras",
  "pepino",
  "pelones",
  "platano",
  "queso",
  "zanahoria",
  "zapallito",
  "zukini",
  "zapallo",
]);

export const unitPatterns = [
  { regex: /\bpor\s*kg\b/i, unit: "Kg" },
  { regex: /\bkgs?\b/i, unit: "Kg" },
  { regex: /\bk\b/i, unit: "Kg" },
  { regex: /\bkilo\b/i, unit: "Kg" },
  { regex: /\bcaj[oó]n\b/i, unit: "Cajón" },
  { regex: /\bcaja\b/i, unit: "Caja" },
  { regex: /\bbandeja\b/i, unit: "Bandeja" },
  { regex: /\bgrande\s+jaula\b/i, unit: "Jaula Grande" },
  { regex: /\bjaula\b/i, unit: "Jaula" },
  { regex: /\bbolsa\b/i, unit: "Bolsa" },
  { regex: /\bdocena\b/i, unit: "Docena" },
  { regex: /\bmaple\b/i, unit: "Maple" },
  { regex: /\bhorma\b/i, unit: "Horma" },
  { regex: /\bpote\b/i, unit: "Pote" },
  { regex: /\batado\b/i, unit: "Atado" },
  { regex: /\bunidad\b/i, unit: "Unidad" },
  { regex: /\b1\/4\b/i, unit: "1/4" },
  { regex: /\bcabeza\b/i, unit: "Cabeza" },
  { regex: /\bristra\b/i, unit: "Ristra" },
  { regex: /\bentero\b/i, unit: "Entero" },
];

export const unitSynonyms = [
  { regex: /^doc(ena)?s?\b/i, unit: "Docena" },
  { regex: /^(gr|g|gramos?)\b/i, unit: "Gr" },
  { regex: /^b\b/i, unit: "Bolsa" },
  { regex: /^planta(s)?\b/i, unit: "Unidad" },
  { regex: /^unid\.?s?(?=\s|$)/i, unit: "Unidad" },
  { regex: /^uni(dad(es)?)?\b/i, unit: "Unidad" },
  { regex: /^pote(s)?\b/i, unit: "Pote" },
  { regex: /^bolsa(s)?\b/i, unit: "Bolsa" },
  { regex: /^jaula(s)?\s+grande(s)?\b/i, unit: "Jaula Grande" },
  { regex: /^jaula(s)?\b/i, unit: "Jaula" },
  { regex: /^caj[oó]n(es)?\b/i, unit: "Cajón" },
  { regex: /^caja(s)?\b/i, unit: "Caja" },
  { regex: /^bandeja(s)?\b/i, unit: "Bandeja" },
  { regex: /^maple(s)?\b/i, unit: "Maple" },
  { regex: /^horma(s)?\b/i, unit: "Horma" },
  { regex: /^atado(s)?\b/i, unit: "Atado" },
  { regex: /^kgs?\b/i, unit: "Kg" },
  { regex: /^kh\b/i, unit: "Kg" },
  { regex: /^k\b/i, unit: "Kg" },
  { regex: /^kilo(s)?\b/i, unit: "Kg" },
  { regex: /^1\s*\/\s*4\b/i, unit: "1/4" },
];
